In [9]:
from random import randint
import numpy as np

a = np.array([randint(-100, 100) for x in range(15)])
b = np.array([randint(0, 1) for x in range(15)])

print(a)
print(b)

c = a[b == 1]
d = a[b == 0]

print(c)
print(d)

[  8  75 -99 -18  -6  27  44  18 -53   3   2 -85  83 -11 -94]
[1 1 0 0 1 1 1 1 1 1 0 0 1 1 1]
[  8  75  -6  27  44  18 -53   3  83 -11 -94]
[-99 -18   2 -85]
